version: '3'

services:
  chades:
    image: httpd
    container_name: chades
    restart: always
    volumes:
      - ./assets:/usr/local/apache2/htdocs/assets
      - ./index.html:/usr/local/apache2/htdocs/index.html
    ports:
      - 8079:80